"""
Run every queries/*.cypher against the graph and emit a findings report.

Each .cypher file starts with a `// TITLE:` line and a `// WHY:` block (the analytical
question and why signatures miss it), followed by a single Cypher statement. This script
strips the header, runs the statement, and writes:

    out/findings.md    human-readable report (tables capped for readability)
    out/findings.json  full machine-readable results

Usage:  python src/run_queries.py     (env: NEO4J_URI, NEO4J_USER, NEO4J_PASS)
"""

import json
import os
from pathlib import Path

from neo4j import GraphDatabase

URI = os.environ.get("NEO4J_URI", "bolt://localhost:7687")
USER = os.environ.get("NEO4J_USER", "neo4j")
PASS = os.environ.get("NEO4J_PASS", "detgap-thesis")

ROOT = Path(__file__).resolve().parents[1]
QDIR = ROOT / "queries"
OUT = ROOT / "out"
MAX_ROWS_MD = 40


def parse_query_file(path: Path):
    title, why, body = path.stem, [], []
    for line in path.read_text().splitlines():
        s = line.strip()
        if s.startswith("// TITLE:"):
            title = s[len("// TITLE:"):].strip()
        elif s.startswith("// WHY:") or s.startswith("//"):
            txt = s.lstrip("/").strip()
            if txt.startswith("WHY:"):
                txt = txt[len("WHY:"):].strip()
            if txt:
                why.append(txt)
        else:
            body.append(line)
    return title, " ".join(why), "\n".join(body).strip()


def cell(v):
    if isinstance(v, list):
        return ", ".join(str(x) for x in v)
    return "" if v is None else str(v)


def md_table(rows):
    if not rows:
        return "_no rows_\n"
    cols = list(rows[0].keys())
    out = ["| " + " | ".join(cols) + " |",
           "| " + " | ".join("---" for _ in cols) + " |"]
    for r in rows[:MAX_ROWS_MD]:
        out.append("| " + " | ".join(cell(r.get(c)) for c in cols) + " |")
    tail = ""
    if len(rows) > MAX_ROWS_MD:
        tail = f"\n_… {len(rows) - MAX_ROWS_MD} more rows (see findings.json)_\n"
    return "\n".join(out) + "\n" + tail


def main():
    OUT.mkdir(exist_ok=True)
    driver = GraphDatabase.driver(URI, auth=(USER, PASS))
    driver.verify_connectivity()

    md = ["# GCP Detection-Gap Findings",
          "",
          "Generated by `graph/run_queries.py` over the Neo4j graph built from four GCP",
          "detection corpora (Sigma, Elastic, Google SecOps, Panther) joined to the",
          "hacktricks-cloud GCP technique corpus on the canonical IAM permission. Every",
          "finding is a **pure graph query** — no ML model is involved.",
          ""]
    all_json = {}

    with driver.session() as s:
        for path in sorted(QDIR.glob("*.cypher")):
            title, why, query = parse_query_file(path)
            rows = [r.data() for r in s.run(query)]
            all_json[path.name] = {"title": title, "why": why,
                                   "row_count": len(rows), "rows": rows}
            print(f"[{path.name}] {title}  -> {len(rows)} rows")
            md += [f"## {path.stem} — {title}", "",
                   f"> {why}", "",
                   f"**{len(rows)} rows.**", "",
                   md_table(rows), ""]

    driver.close()
    (OUT / "findings.md").write_text("\n".join(md))
    (OUT / "findings.json").write_text(json.dumps(all_json, indent=2, default=str))
    print(f"\nwrote {OUT/'findings.md'} and {OUT/'findings.json'}")


if __name__ == "__main__":
    main()
